_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 75573f05-2623-4bfe-b3f4-94b09be2c998
name: 'Indicator Registry'
mail: admin@example.com
slogan: ''
page:
  403: /
  404: /
  front: /node/138926
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
