name: Test docker image

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Determine environment type
      uses: docker://unocha/actions:determine-environment-v3
    - name: Test build docker image
      run: |
        docker build \
            --build-arg BRANCH_ENVIRONMENT=${BRANCH_ENVIRONMENT} \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VCS_URL=`git config --get remote.origin.url | sed 's#git@github.com:#https://github.com/#'` \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg GITHUB_ACTOR=${GITHUB_ACTOR} \
            --build-arg GITHUB_REPOSITORY=${GITHUB_REPOSITORY} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg GITHUB_REF=${GITHUB_REF} \
         . --file docker/Dockerfile
